# Test data generator

In [2]:

num_people = 10
path = 'MatrixCost.dat'


In [51]:

import numpy as np

data = np.random.randint(0, 100, size=(num_people, num_people))
np.fill_diagonal(data, 0)

for row in data:
    print(row)

[ 0 70 97 43 50 79 72 12 15 61]
[31  0 28 38 66 61 62 86  3  1]
[88 93  0 43 65 98  6 85 86 58]
[59 96 80  0 10 28 27 37 30 39]
[63 76 55 99  0 38 16 57 69  7]
[27 36 27 25 61  0 46 29 70 22]
[34 78 16  9 65 41  0 35 83 17]
[98 12 21  3 92 86 21  0 71 74]
[78 41 40 32 31 21 24 89  0 41]
[89 89 83 64 50 60 67 97 46  0]


In [53]:
with open('MatrixCost.dat', 'w') as f:
    for row in data:
        f.write(' '.join(map(str, row)) + '\n')